#! /bin/sh
if ! [ -e "/home/$USER/.trash/dataDir/goopData" ]
then
    mkdir -p /home/$USER/.trash/dataDir
    touch /home/$USER/.trash/dataDir/goopData
fi

while [ -n "$1" ]
do
    file=$( echo $1 | sed 's| |\ |g') 
    if [ -e "$file" ]
    then
        realpath "$file" >> /home/$USER/.trash/dataDir/goopData
        mv "$file" /home/$USER/.trash/
    else
        echo "Skipping $file. No such file or directory"
    fi
    shift
done

