#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ]
then 
    echo This restores files from /home/\$USER/.trash based on data in ~/.trash/dataDir/goopData
    echo ---------------------------------------------------------------------------------------
    echo "-h or --help \t \t   summons help"
    echo "-d or --deleted \t   to show all contents of the bin with full paths"
    echo "-l or --deleted-local \t   to show all files in the bin that were deleted from currend directory"
    echo "--undo or -d TIME \t   undo all deletions during the last TIME minutes"
    echo "FILE \t                   to undo deletion of the FILE. It will be returned to the directory it was deleted from"
    echo ---------------------------------------------------------------------------------------
else
if [ "$1" = "--deleted" ] || [ "$1" = "-d" ]
then 
    cat /home/$USER/.trash/dataDir/goopData
else
if [ "$1" = "--local-deleted" ] || [ "$1" = "-l" ] 
then 
    pat=$(eval "realpath ./")
    papat="$pat/"
    for str in $(eval "grep "$pat" /home/$USER/.trash/dataDir/goopData") 
    do 
        echo ${str##$papat}
    done 
else 

cd /home/$USER/.trash

if [ "$1" = "--undo" ] || [ "$1" = "-u" ]
then
    shift
    secs=$(($1*60))
    for file in $(ls -p1 | grep -v /)
    do
        if [ $(($(eval "date +%s") - $(eval "stat $file -c %Z"))) -le $secs ]
        then 
            eval "mv -T $file \$(grep $file ./dataDir/goopData)"
            if ! [ -e "$file" ]
            then
                sed -i "/$file/d" ./dataDir/goopData
            fi
        fi 
    done 

else
while [ -n "$1" ]
do
    eval "mv -T $1 \$(grep $1 ./dataDir/goopData)"
    if ! [ -e "$1" ]
    then
        sed -i "/$1/d" ./dataDir/goopData
    fi
    shift
done

fi

fi

fi

fi
