#! /bin/bash
IFS=$'\n'

while [ -n "$1" ]
do
case $1 in 

    "--help"|"-h")
        echo "This restores files from /home/$USER/.trash based on data in /home/$USER/.trash/dataDir/goopData"
        echo ---------------------------------------------------------------------------------------
        echo -e "--help or -h \t \t   summons help"
        echo -e "--deleted or -d \t   to show all contents of the bin with full paths"
        echo -e "--deleted-local or -l  \t   to show all files in the bin that were deleted from currend directory"
        echo -e "--undo or -u TIME \t   undo all deletions during the last TIME minutes"
        echo -e "--clear or -c FILE.. \t   to remove files from the bin"
        echo -e "--move-here or -m FILE..   to restore files to the current directory"
        echo -e "FILE \t                   to undo deletion of the FILE. It will be returned to the directory it was deleted from"
        echo ---------------------------------------------------------------------------------------
        shift
    ;;

    "--deleted"|"-d")
        cat /home/$USER/.trash/dataDir/goopData
        shift
    ;;

    "--local-deleted"|"-l")
        pat=$(eval "realpath ./")
        slashpat="$pat/"
        for str in $(eval "grep "$pat" /home/$USER/.trash/dataDir/goopData") 
        do 
            filepat=${str##$slashpat}
            if [ -z "$(eval echo $filepat |  grep "/" )" ]
            then 
                echo $filepat
            fi
        done 
        shift
    ;;

    "--undo"|"-u")
        cd /home/$USER/.trash
        shift
        secs=$(($1*60))
        for somefile in $(ls -p1 | grep -v /)
        do
            file=$(eval sed "'s|[^[:alnum:]]|\\\&|g'" <<< "$somefile")
            if [ $(($(eval "date +%s") - $(eval stat "$file" -c %Z))) -le $secs ]
            then 
                fileForGrep=$(eval sed "'s|\\\\|\\\\\\\|g'" <<< "$file")
                pathToFile=$(eval grep -m 1 "'$fileForGrep'" ./dataDir/goopData)
                if [ -n "$pathToFile" ]
                then
                    eval "mv -T $file $pathToFile"
                    if ! [ -e "$1" ]
                    then
                        echo "Restored $pathToFile"
                        sed -i "/$fileForGrep/d" ./dataDir/goopData
                    fi
                else 
                    echo "$file is not in the bin"
                fi
           fi 
        done 
        shift
    ;;

    "-c"|"--clear")
        shift
        while [ -n "$1" ]
        do
            cd /home/$USER/.trash 
            file=$(eval sed "'s|[^[:alnum:]]|\\\&|g'" <<< "$1")
            fileForGrep=$(eval sed "'s|\\\\|\\\\\\\|g'" <<< "$file")
            rm ./$file
            sed -i "/$fileForGrep/d" ./dataDir/goopData
            echo "$file deleted forever"
            shift
        done
    ;;        

    "-m"|"--move-here")
        shift
        pat=$(eval "realpath ./")
        escpath=$(eval sed "'s|[^[:alnum:]]|\\\&|g'" <<< "$pat")      
        while [ -n "$1" ]
        do
            file=$(eval sed "'s|[^[:alnum:]]|\\\&|g'" <<< "$1")
            fileForGrep=$(eval sed "'s|\\\\|\\\\\\\|g'" <<< "$file")
            if [ -e "/home/$USER/.trash/$1" ] 
            then
                eval "mv /home/$USER/.trash/$file $escpath/"
                if ! [ -e "/home/$USER/.trash/$file" ]
                then
                    echo "Restored $file to this directory"
                    sed -i "/$fileForGrep/d" /home/$USER/.trash/dataDir/goopData
                fi
            else 
                echo "$file is not in the bin"
            fi
            shift
        done
        ;;

    *)
        cd /home/$USER/.trash
        file=$(eval sed "'s|[^[:alnum:]]|\\\&|g'" <<< "$1")
        fileForGrep=$(eval sed "'s|\\\\|\\\\\\\|g'" <<< "$file")
        pathToFile=$(eval grep -m 1 "'$fileForGrep'" ./dataDir/goopData)
        if [ -n "$pathToFile" ]
        then
            eval "mv -T $file $pathToFile"
            if ! [ -e "$1" ]
            then
                echo "Restored $pathToFile"
                sed -i "/$fileForGrep/d" ./dataDir/goopData
            fi
        else 
            echo "$file is not in the bin"
        fi
        shift
    ;;

esac

done

