#! /bin/bash
if ! [ -e "/home/$USER/.trash/dataDir/goopData" ]
then
    mkdir -p /home/$USER/.trash/dataDir
    touch /home/$USER/.trash/dataDir/goopData
fi

while [ -n "$1" ]
do
    if [ -e "$1" ]
    then
        if [ "$(eval grep -c "'[ \\\\!?)([<>%\$\*-,;=^\`|.:]'" <<< "$1")" != "0" ]
        then
            file=$(eval sed "'s|[ \\\\\\!?)([<>%\$*-,;=^\`|.:]|\\\\&|g'" <<< "$1")
        else 
            file=$1
        fi
        realpath "$file" >> /home/$USER/.trash/dataDir/goopData
        mv "$1" /home/$USER/.trash/
        echo "$file moved to bin"
    else
        echo "Skipping $1. No such file or directory"
    fi
    shift
done

