#! /bin/sh
while [ -n "$1" ]
do
    if [ -e "$1" ]
    then
        realpath $1 >> /home/$USER/.trash/dataDir/goopData
        mv $1 /home/$USER/.trash/
    else
        echo "Skipping $1. No such file or directory"
    fi
    shift
done

